sudo: required
services:
  - docker

language: php 

php:
  - 5.4
  - 5.5
  - 5.6

python:
  - "2.7"

cache: false

virtualenv:
    system_site_packages: true

env:
    matrix:
      - OS=el DIST=6 PACK=rpm
      - OS=el DIST=7 PACK=rpm
      - OS=fedora DIST=20 PACK=rpm
      - OS=fedora DIST=21 PACK=rpm
      - OS=fedora DIST=22 PACK=rpm
      - OS=fedora DIST=23 PACK=rpm
      - OS=ubuntu DIST=trusty PACK=deb
      - OS=ubuntu DIST=precise PACK=deb
      - OS=ubuntu DIST=vivid PACK=deb
      - OS=debian DIST=jessie PACK=deb
      - OS=debian DIST=wheezy PACK=deb
      - OS=debian DIST=stretch PACK=deb
      - PACK=none

# multiple php version exclusion matrix
matrix:
    exclude:
      - env: OS=el DIST=6 PACK=rpm
        php: 5.3
      - env: OS=el DIST=7 PACK=rpm
        php: 5.3
      - env: OS=fedora DIST=20 PACK=rpm
        php: 5.3
      - env: OS=fedora DIST=21 PACK=rpm
        php: 5.3
      - env: OS=fedora DIST=22 PACK=rpm
        php: 5.3
      - env: OS=fedora DIST=23 PACK=rpm
        php: 5.3
      - env: OS=ubuntu DIST=trusty PACK=deb
        php: 5.3
      - env: OS=ubuntu DIST=precise PACK=deb
        php: 5.3
      - env: OS=ubuntu DIST=vivid PACK=deb
        php: 5.3
      - env: OS=debian DIST=jessie PACK=deb
        php: 5.3
      - env: OS=debian DIST=wheezy PACK=deb
        php: 5.3
      - env: OS=debian DIST=stretch PACK=deb
        php: 5.3
      - env: OS=el DIST=6 PACK=rpm
        php: 5.4
      - env: OS=el DIST=7 PACK=rpm
        php: 5.4
      - env: OS=fedora DIST=20 PACK=rpm
        php: 5.4
      - env: OS=fedora DIST=21 PACK=rpm
        php: 5.4
      - env: OS=fedora DIST=22 PACK=rpm
        php: 5.4
      - env: OS=fedora DIST=23 PACK=rpm
        php: 5.4
      - env: OS=ubuntu DIST=trusty PACK=deb
        php: 5.4
      - env: OS=ubuntu DIST=precise PACK=deb
        php: 5.4
      - env: OS=ubuntu DIST=vivid PACK=deb
        php: 5.4
      - env: OS=debian DIST=jessie PACK=deb
        php: 5.4
      - env: OS=debian DIST=wheezy PACK=deb
        php: 5.4
      - env: OS=debian DIST=stretch PACK=deb
        php: 5.4
      - env: OS=el DIST=6 PACK=rpm
        php: 5.5
      - env: OS=el DIST=7 PACK=rpm
        php: 5.5
      - env: OS=fedora DIST=20 PACK=rpm
        php: 5.5
      - env: OS=fedora DIST=21 PACK=rpm
        php: 5.5
      - env: OS=fedora DIST=22 PACK=rpm
        php: 5.5
      - env: OS=fedora DIST=23 PACK=rpm
        php: 5.5
      - env: OS=ubuntu DIST=trusty PACK=deb
        php: 5.5
      - env: OS=ubuntu DIST=precise PACK=deb
        php: 5.5
      - env: OS=ubuntu DIST=vivid PACK=deb
        php: 5.5
      - env: OS=debian DIST=jessie PACK=deb
        php: 5.5
      - env: OS=debian DIST=wheezy PACK=deb
        php: 5.5
      - env: OS=debian DIST=stretch PACK=deb
        php: 5.5

script:
  - git clone https://github.com/tarantool/build.git
  - bash build/pack/travis.sh

notifications:
  email: true
  irc: false
