language: php 

branches:
  only:
    - nextgen
    - master

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5

notifications:
  email: false
  irc: false

before_script:
  - uname -a
  - lsb_release -a
  - curl http://tarantool.org/dist/public.key | sudo apt-key add -
  - echo "deb http://tarantool.org/dist/master/ubuntu `lsb-release -c -s`"
  - sudo apt-get update
  - sudo apt-get -y install tarantool

script:
  - phpize && ./configure
  - make
  - ./test-run.py
